// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FkPaintInfo.proto

package com.alimin.fk.pb;

public final class FkPaintInfoOuterClass {
  private FkPaintInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FkPaintInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.alimin.fk.pb.FkPaintInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 strokeWidth = 1;</code>
     * @return The strokeWidth.
     */
    int getStrokeWidth();

    /**
     * <code>int32 color = 2;</code>
     * @return The color.
     */
    int getColor();
  }
  /**
   * Protobuf type {@code com.alimin.fk.pb.FkPaintInfo}
   */
  public static final class FkPaintInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.alimin.fk.pb.FkPaintInfo)
      FkPaintInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FkPaintInfo.newBuilder() to construct.
    private FkPaintInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FkPaintInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FkPaintInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FkPaintInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              strokeWidth_ = input.readInt32();
              break;
            }
            case 16: {

              color_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alimin.fk.pb.FkPaintInfoOuterClass.internal_static_com_alimin_fk_pb_FkPaintInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alimin.fk.pb.FkPaintInfoOuterClass.internal_static_com_alimin_fk_pb_FkPaintInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo.class, com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo.Builder.class);
    }

    public static final int STROKEWIDTH_FIELD_NUMBER = 1;
    private int strokeWidth_;
    /**
     * <code>int32 strokeWidth = 1;</code>
     * @return The strokeWidth.
     */
    @java.lang.Override
    public int getStrokeWidth() {
      return strokeWidth_;
    }

    public static final int COLOR_FIELD_NUMBER = 2;
    private int color_;
    /**
     * <code>int32 color = 2;</code>
     * @return The color.
     */
    @java.lang.Override
    public int getColor() {
      return color_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (strokeWidth_ != 0) {
        output.writeInt32(1, strokeWidth_);
      }
      if (color_ != 0) {
        output.writeInt32(2, color_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (strokeWidth_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, strokeWidth_);
      }
      if (color_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, color_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo)) {
        return super.equals(obj);
      }
      com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo other = (com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo) obj;

      if (getStrokeWidth()
          != other.getStrokeWidth()) return false;
      if (getColor()
          != other.getColor()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STROKEWIDTH_FIELD_NUMBER;
      hash = (53 * hash) + getStrokeWidth();
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.alimin.fk.pb.FkPaintInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.alimin.fk.pb.FkPaintInfo)
        com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alimin.fk.pb.FkPaintInfoOuterClass.internal_static_com_alimin_fk_pb_FkPaintInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alimin.fk.pb.FkPaintInfoOuterClass.internal_static_com_alimin_fk_pb_FkPaintInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo.class, com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo.Builder.class);
      }

      // Construct using com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        strokeWidth_ = 0;

        color_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alimin.fk.pb.FkPaintInfoOuterClass.internal_static_com_alimin_fk_pb_FkPaintInfo_descriptor;
      }

      @java.lang.Override
      public com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo getDefaultInstanceForType() {
        return com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo build() {
        com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo buildPartial() {
        com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo result = new com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo(this);
        result.strokeWidth_ = strokeWidth_;
        result.color_ = color_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo) {
          return mergeFrom((com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo other) {
        if (other == com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo.getDefaultInstance()) return this;
        if (other.getStrokeWidth() != 0) {
          setStrokeWidth(other.getStrokeWidth());
        }
        if (other.getColor() != 0) {
          setColor(other.getColor());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int strokeWidth_ ;
      /**
       * <code>int32 strokeWidth = 1;</code>
       * @return The strokeWidth.
       */
      @java.lang.Override
      public int getStrokeWidth() {
        return strokeWidth_;
      }
      /**
       * <code>int32 strokeWidth = 1;</code>
       * @param value The strokeWidth to set.
       * @return This builder for chaining.
       */
      public Builder setStrokeWidth(int value) {
        
        strokeWidth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 strokeWidth = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStrokeWidth() {
        
        strokeWidth_ = 0;
        onChanged();
        return this;
      }

      private int color_ ;
      /**
       * <code>int32 color = 2;</code>
       * @return The color.
       */
      @java.lang.Override
      public int getColor() {
        return color_;
      }
      /**
       * <code>int32 color = 2;</code>
       * @param value The color to set.
       * @return This builder for chaining.
       */
      public Builder setColor(int value) {
        
        color_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 color = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearColor() {
        
        color_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.alimin.fk.pb.FkPaintInfo)
    }

    // @@protoc_insertion_point(class_scope:com.alimin.fk.pb.FkPaintInfo)
    private static final com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo();
    }

    public static com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FkPaintInfo>
        PARSER = new com.google.protobuf.AbstractParser<FkPaintInfo>() {
      @java.lang.Override
      public FkPaintInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FkPaintInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FkPaintInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FkPaintInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.alimin.fk.pb.FkPaintInfoOuterClass.FkPaintInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alimin_fk_pb_FkPaintInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alimin_fk_pb_FkPaintInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021FkPaintInfo.proto\022\020com.alimin.fk.pb\"1\n" +
      "\013FkPaintInfo\022\023\n\013strokeWidth\030\001 \001(\005\022\r\n\005col" +
      "or\030\002 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_alimin_fk_pb_FkPaintInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_alimin_fk_pb_FkPaintInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alimin_fk_pb_FkPaintInfo_descriptor,
        new java.lang.String[] { "StrokeWidth", "Color", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
