// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FkPictureModel.proto

package com.alimin.fk.pb;

public final class FkPictureModelOuterClass {
  private FkPictureModelOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FkPictureModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.alimin.fk.pb.FkPictureModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.alimin.fk.pb.FkImageLayer canvas = 1;</code>
     * @return Whether the canvas field is set.
     */
    boolean hasCanvas();
    /**
     * <code>.com.alimin.fk.pb.FkImageLayer canvas = 1;</code>
     * @return The canvas.
     */
    com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer getCanvas();
    /**
     * <code>.com.alimin.fk.pb.FkImageLayer canvas = 1;</code>
     */
    com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayerOrBuilder getCanvasOrBuilder();

    /**
     * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
     */
    java.util.List<com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer> 
        getLayersList();
    /**
     * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
     */
    com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer getLayers(int index);
    /**
     * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
     */
    int getLayersCount();
    /**
     * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
     */
    java.util.List<? extends com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayerOrBuilder> 
        getLayersOrBuilderList();
    /**
     * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
     */
    com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayerOrBuilder getLayersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.alimin.fk.pb.FkPictureModel}
   */
  public static final class FkPictureModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.alimin.fk.pb.FkPictureModel)
      FkPictureModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FkPictureModel.newBuilder() to construct.
    private FkPictureModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FkPictureModel() {
      layers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FkPictureModel();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FkPictureModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.Builder subBuilder = null;
              if (canvas_ != null) {
                subBuilder = canvas_.toBuilder();
              }
              canvas_ = input.readMessage(com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(canvas_);
                canvas_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                layers_ = new java.util.ArrayList<com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer>();
                mutable_bitField0_ |= 0x00000001;
              }
              layers_.add(
                  input.readMessage(com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          layers_ = java.util.Collections.unmodifiableList(layers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alimin.fk.pb.FkPictureModelOuterClass.internal_static_com_alimin_fk_pb_FkPictureModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alimin.fk.pb.FkPictureModelOuterClass.internal_static_com_alimin_fk_pb_FkPictureModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel.class, com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel.Builder.class);
    }

    public static final int CANVAS_FIELD_NUMBER = 1;
    private com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer canvas_;
    /**
     * <code>.com.alimin.fk.pb.FkImageLayer canvas = 1;</code>
     * @return Whether the canvas field is set.
     */
    @java.lang.Override
    public boolean hasCanvas() {
      return canvas_ != null;
    }
    /**
     * <code>.com.alimin.fk.pb.FkImageLayer canvas = 1;</code>
     * @return The canvas.
     */
    @java.lang.Override
    public com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer getCanvas() {
      return canvas_ == null ? com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.getDefaultInstance() : canvas_;
    }
    /**
     * <code>.com.alimin.fk.pb.FkImageLayer canvas = 1;</code>
     */
    @java.lang.Override
    public com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayerOrBuilder getCanvasOrBuilder() {
      return getCanvas();
    }

    public static final int LAYERS_FIELD_NUMBER = 2;
    private java.util.List<com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer> layers_;
    /**
     * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer> getLayersList() {
      return layers_;
    }
    /**
     * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayerOrBuilder> 
        getLayersOrBuilderList() {
      return layers_;
    }
    /**
     * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
     */
    @java.lang.Override
    public int getLayersCount() {
      return layers_.size();
    }
    /**
     * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
     */
    @java.lang.Override
    public com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer getLayers(int index) {
      return layers_.get(index);
    }
    /**
     * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
     */
    @java.lang.Override
    public com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayerOrBuilder getLayersOrBuilder(
        int index) {
      return layers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (canvas_ != null) {
        output.writeMessage(1, getCanvas());
      }
      for (int i = 0; i < layers_.size(); i++) {
        output.writeMessage(2, layers_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (canvas_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCanvas());
      }
      for (int i = 0; i < layers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, layers_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel)) {
        return super.equals(obj);
      }
      com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel other = (com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel) obj;

      if (hasCanvas() != other.hasCanvas()) return false;
      if (hasCanvas()) {
        if (!getCanvas()
            .equals(other.getCanvas())) return false;
      }
      if (!getLayersList()
          .equals(other.getLayersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCanvas()) {
        hash = (37 * hash) + CANVAS_FIELD_NUMBER;
        hash = (53 * hash) + getCanvas().hashCode();
      }
      if (getLayersCount() > 0) {
        hash = (37 * hash) + LAYERS_FIELD_NUMBER;
        hash = (53 * hash) + getLayersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.alimin.fk.pb.FkPictureModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.alimin.fk.pb.FkPictureModel)
        com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alimin.fk.pb.FkPictureModelOuterClass.internal_static_com_alimin_fk_pb_FkPictureModel_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alimin.fk.pb.FkPictureModelOuterClass.internal_static_com_alimin_fk_pb_FkPictureModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel.class, com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel.Builder.class);
      }

      // Construct using com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLayersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (canvasBuilder_ == null) {
          canvas_ = null;
        } else {
          canvas_ = null;
          canvasBuilder_ = null;
        }
        if (layersBuilder_ == null) {
          layers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          layersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alimin.fk.pb.FkPictureModelOuterClass.internal_static_com_alimin_fk_pb_FkPictureModel_descriptor;
      }

      @java.lang.Override
      public com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel getDefaultInstanceForType() {
        return com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel.getDefaultInstance();
      }

      @java.lang.Override
      public com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel build() {
        com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel buildPartial() {
        com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel result = new com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel(this);
        int from_bitField0_ = bitField0_;
        if (canvasBuilder_ == null) {
          result.canvas_ = canvas_;
        } else {
          result.canvas_ = canvasBuilder_.build();
        }
        if (layersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            layers_ = java.util.Collections.unmodifiableList(layers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.layers_ = layers_;
        } else {
          result.layers_ = layersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel) {
          return mergeFrom((com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel other) {
        if (other == com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel.getDefaultInstance()) return this;
        if (other.hasCanvas()) {
          mergeCanvas(other.getCanvas());
        }
        if (layersBuilder_ == null) {
          if (!other.layers_.isEmpty()) {
            if (layers_.isEmpty()) {
              layers_ = other.layers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLayersIsMutable();
              layers_.addAll(other.layers_);
            }
            onChanged();
          }
        } else {
          if (!other.layers_.isEmpty()) {
            if (layersBuilder_.isEmpty()) {
              layersBuilder_.dispose();
              layersBuilder_ = null;
              layers_ = other.layers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              layersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLayersFieldBuilder() : null;
            } else {
              layersBuilder_.addAllMessages(other.layers_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer canvas_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.Builder, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayerOrBuilder> canvasBuilder_;
      /**
       * <code>.com.alimin.fk.pb.FkImageLayer canvas = 1;</code>
       * @return Whether the canvas field is set.
       */
      public boolean hasCanvas() {
        return canvasBuilder_ != null || canvas_ != null;
      }
      /**
       * <code>.com.alimin.fk.pb.FkImageLayer canvas = 1;</code>
       * @return The canvas.
       */
      public com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer getCanvas() {
        if (canvasBuilder_ == null) {
          return canvas_ == null ? com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.getDefaultInstance() : canvas_;
        } else {
          return canvasBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.alimin.fk.pb.FkImageLayer canvas = 1;</code>
       */
      public Builder setCanvas(com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer value) {
        if (canvasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          canvas_ = value;
          onChanged();
        } else {
          canvasBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.alimin.fk.pb.FkImageLayer canvas = 1;</code>
       */
      public Builder setCanvas(
          com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.Builder builderForValue) {
        if (canvasBuilder_ == null) {
          canvas_ = builderForValue.build();
          onChanged();
        } else {
          canvasBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.alimin.fk.pb.FkImageLayer canvas = 1;</code>
       */
      public Builder mergeCanvas(com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer value) {
        if (canvasBuilder_ == null) {
          if (canvas_ != null) {
            canvas_ =
              com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.newBuilder(canvas_).mergeFrom(value).buildPartial();
          } else {
            canvas_ = value;
          }
          onChanged();
        } else {
          canvasBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.alimin.fk.pb.FkImageLayer canvas = 1;</code>
       */
      public Builder clearCanvas() {
        if (canvasBuilder_ == null) {
          canvas_ = null;
          onChanged();
        } else {
          canvas_ = null;
          canvasBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.alimin.fk.pb.FkImageLayer canvas = 1;</code>
       */
      public com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.Builder getCanvasBuilder() {
        
        onChanged();
        return getCanvasFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.alimin.fk.pb.FkImageLayer canvas = 1;</code>
       */
      public com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayerOrBuilder getCanvasOrBuilder() {
        if (canvasBuilder_ != null) {
          return canvasBuilder_.getMessageOrBuilder();
        } else {
          return canvas_ == null ?
              com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.getDefaultInstance() : canvas_;
        }
      }
      /**
       * <code>.com.alimin.fk.pb.FkImageLayer canvas = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.Builder, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayerOrBuilder> 
          getCanvasFieldBuilder() {
        if (canvasBuilder_ == null) {
          canvasBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.Builder, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayerOrBuilder>(
                  getCanvas(),
                  getParentForChildren(),
                  isClean());
          canvas_ = null;
        }
        return canvasBuilder_;
      }

      private java.util.List<com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer> layers_ =
        java.util.Collections.emptyList();
      private void ensureLayersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          layers_ = new java.util.ArrayList<com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer>(layers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.Builder, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayerOrBuilder> layersBuilder_;

      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public java.util.List<com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer> getLayersList() {
        if (layersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(layers_);
        } else {
          return layersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public int getLayersCount() {
        if (layersBuilder_ == null) {
          return layers_.size();
        } else {
          return layersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer getLayers(int index) {
        if (layersBuilder_ == null) {
          return layers_.get(index);
        } else {
          return layersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public Builder setLayers(
          int index, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer value) {
        if (layersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLayersIsMutable();
          layers_.set(index, value);
          onChanged();
        } else {
          layersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public Builder setLayers(
          int index, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.Builder builderForValue) {
        if (layersBuilder_ == null) {
          ensureLayersIsMutable();
          layers_.set(index, builderForValue.build());
          onChanged();
        } else {
          layersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public Builder addLayers(com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer value) {
        if (layersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLayersIsMutable();
          layers_.add(value);
          onChanged();
        } else {
          layersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public Builder addLayers(
          int index, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer value) {
        if (layersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLayersIsMutable();
          layers_.add(index, value);
          onChanged();
        } else {
          layersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public Builder addLayers(
          com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.Builder builderForValue) {
        if (layersBuilder_ == null) {
          ensureLayersIsMutable();
          layers_.add(builderForValue.build());
          onChanged();
        } else {
          layersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public Builder addLayers(
          int index, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.Builder builderForValue) {
        if (layersBuilder_ == null) {
          ensureLayersIsMutable();
          layers_.add(index, builderForValue.build());
          onChanged();
        } else {
          layersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public Builder addAllLayers(
          java.lang.Iterable<? extends com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer> values) {
        if (layersBuilder_ == null) {
          ensureLayersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, layers_);
          onChanged();
        } else {
          layersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public Builder clearLayers() {
        if (layersBuilder_ == null) {
          layers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          layersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public Builder removeLayers(int index) {
        if (layersBuilder_ == null) {
          ensureLayersIsMutable();
          layers_.remove(index);
          onChanged();
        } else {
          layersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.Builder getLayersBuilder(
          int index) {
        return getLayersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayerOrBuilder getLayersOrBuilder(
          int index) {
        if (layersBuilder_ == null) {
          return layers_.get(index);  } else {
          return layersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public java.util.List<? extends com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayerOrBuilder> 
           getLayersOrBuilderList() {
        if (layersBuilder_ != null) {
          return layersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(layers_);
        }
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.Builder addLayersBuilder() {
        return getLayersFieldBuilder().addBuilder(
            com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.getDefaultInstance());
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.Builder addLayersBuilder(
          int index) {
        return getLayersFieldBuilder().addBuilder(
            index, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.getDefaultInstance());
      }
      /**
       * <code>repeated .com.alimin.fk.pb.FkImageLayer layers = 2;</code>
       */
      public java.util.List<com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.Builder> 
           getLayersBuilderList() {
        return getLayersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.Builder, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayerOrBuilder> 
          getLayersFieldBuilder() {
        if (layersBuilder_ == null) {
          layersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayer.Builder, com.alimin.fk.pb.FkImageLayerOuterClass.FkImageLayerOrBuilder>(
                  layers_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          layers_ = null;
        }
        return layersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.alimin.fk.pb.FkPictureModel)
    }

    // @@protoc_insertion_point(class_scope:com.alimin.fk.pb.FkPictureModel)
    private static final com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel();
    }

    public static com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FkPictureModel>
        PARSER = new com.google.protobuf.AbstractParser<FkPictureModel>() {
      @java.lang.Override
      public FkPictureModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FkPictureModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FkPictureModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FkPictureModel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.alimin.fk.pb.FkPictureModelOuterClass.FkPictureModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alimin_fk_pb_FkPictureModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alimin_fk_pb_FkPictureModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024FkPictureModel.proto\022\020com.alimin.fk.pb" +
      "\032\022FkImageLayer.proto\"p\n\016FkPictureModel\022." +
      "\n\006canvas\030\001 \001(\0132\036.com.alimin.fk.pb.FkImag" +
      "eLayer\022.\n\006layers\030\002 \003(\0132\036.com.alimin.fk.p" +
      "b.FkImageLayerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.alimin.fk.pb.FkImageLayerOuterClass.getDescriptor(),
        });
    internal_static_com_alimin_fk_pb_FkPictureModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_alimin_fk_pb_FkPictureModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alimin_fk_pb_FkPictureModel_descriptor,
        new java.lang.String[] { "Canvas", "Layers", });
    com.alimin.fk.pb.FkImageLayerOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
