// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FkImageLayer.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_FkImageLayer_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_FkImageLayer_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "FkSize.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_FkImageLayer_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_FkImageLayer_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_FkImageLayer_2eproto;
namespace fk_pb {
class FkImageLayer;
struct FkImageLayerDefaultTypeInternal;
extern FkImageLayerDefaultTypeInternal _FkImageLayer_default_instance_;
}  // namespace fk_pb
PROTOBUF_NAMESPACE_OPEN
template<> ::fk_pb::FkImageLayer* Arena::CreateMaybeMessage<::fk_pb::FkImageLayer>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace fk_pb {

// ===================================================================

class FkImageLayer final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fk_pb.FkImageLayer) */ {
 public:
  inline FkImageLayer() : FkImageLayer(nullptr) {}
  ~FkImageLayer() override;
  explicit constexpr FkImageLayer(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FkImageLayer(const FkImageLayer& from);
  FkImageLayer(FkImageLayer&& from) noexcept
    : FkImageLayer() {
    *this = ::std::move(from);
  }

  inline FkImageLayer& operator=(const FkImageLayer& from) {
    CopyFrom(from);
    return *this;
  }
  inline FkImageLayer& operator=(FkImageLayer&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FkImageLayer& default_instance() {
    return *internal_default_instance();
  }
  static inline const FkImageLayer* internal_default_instance() {
    return reinterpret_cast<const FkImageLayer*>(
               &_FkImageLayer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FkImageLayer& a, FkImageLayer& b) {
    a.Swap(&b);
  }
  inline void Swap(FkImageLayer* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FkImageLayer* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FkImageLayer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FkImageLayer>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FkImageLayer& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const FkImageLayer& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FkImageLayer* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fk_pb.FkImageLayer";
  }
  protected:
  explicit FkImageLayer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSizeFieldNumber = 1,
  };
  // .fk_pb.FkSize size = 1;
  bool has_size() const;
  private:
  bool _internal_has_size() const;
  public:
  void clear_size();
  const ::fk_pb::FkSize& size() const;
  PROTOBUF_NODISCARD ::fk_pb::FkSize* release_size();
  ::fk_pb::FkSize* mutable_size();
  void set_allocated_size(::fk_pb::FkSize* size);
  private:
  const ::fk_pb::FkSize& _internal_size() const;
  ::fk_pb::FkSize* _internal_mutable_size();
  public:
  void unsafe_arena_set_allocated_size(
      ::fk_pb::FkSize* size);
  ::fk_pb::FkSize* unsafe_arena_release_size();

  // @@protoc_insertion_point(class_scope:fk_pb.FkImageLayer)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::fk_pb::FkSize* size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_FkImageLayer_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FkImageLayer

// .fk_pb.FkSize size = 1;
inline bool FkImageLayer::_internal_has_size() const {
  return this != internal_default_instance() && size_ != nullptr;
}
inline bool FkImageLayer::has_size() const {
  return _internal_has_size();
}
inline const ::fk_pb::FkSize& FkImageLayer::_internal_size() const {
  const ::fk_pb::FkSize* p = size_;
  return p != nullptr ? *p : reinterpret_cast<const ::fk_pb::FkSize&>(
      ::fk_pb::_FkSize_default_instance_);
}
inline const ::fk_pb::FkSize& FkImageLayer::size() const {
  // @@protoc_insertion_point(field_get:fk_pb.FkImageLayer.size)
  return _internal_size();
}
inline void FkImageLayer::unsafe_arena_set_allocated_size(
    ::fk_pb::FkSize* size) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(size_);
  }
  size_ = size;
  if (size) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fk_pb.FkImageLayer.size)
}
inline ::fk_pb::FkSize* FkImageLayer::release_size() {
  
  ::fk_pb::FkSize* temp = size_;
  size_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::fk_pb::FkSize* FkImageLayer::unsafe_arena_release_size() {
  // @@protoc_insertion_point(field_release:fk_pb.FkImageLayer.size)
  
  ::fk_pb::FkSize* temp = size_;
  size_ = nullptr;
  return temp;
}
inline ::fk_pb::FkSize* FkImageLayer::_internal_mutable_size() {
  
  if (size_ == nullptr) {
    auto* p = CreateMaybeMessage<::fk_pb::FkSize>(GetArenaForAllocation());
    size_ = p;
  }
  return size_;
}
inline ::fk_pb::FkSize* FkImageLayer::mutable_size() {
  ::fk_pb::FkSize* _msg = _internal_mutable_size();
  // @@protoc_insertion_point(field_mutable:fk_pb.FkImageLayer.size)
  return _msg;
}
inline void FkImageLayer::set_allocated_size(::fk_pb::FkSize* size) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(size_);
  }
  if (size) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(size));
    if (message_arena != submessage_arena) {
      size = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, size, submessage_arena);
    }
    
  } else {
    
  }
  size_ = size;
  // @@protoc_insertion_point(field_set_allocated:fk_pb.FkImageLayer.size)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace fk_pb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_FkImageLayer_2eproto
