// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FkPictureModel.proto

#include "FkPictureModel.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace com {
namespace alimin {
namespace fk {
namespace pb {
constexpr FkPictureModel::FkPictureModel(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : layers_()
  , canvas_(nullptr){}
struct FkPictureModelDefaultTypeInternal {
  constexpr FkPictureModelDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~FkPictureModelDefaultTypeInternal() {}
  union {
    FkPictureModel _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT FkPictureModelDefaultTypeInternal _FkPictureModel_default_instance_;
}  // namespace pb
}  // namespace fk
}  // namespace alimin
}  // namespace com
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_FkPictureModel_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_FkPictureModel_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_FkPictureModel_2eproto = nullptr;

const uint32_t TableStruct_FkPictureModel_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::alimin::fk::pb::FkPictureModel, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::com::alimin::fk::pb::FkPictureModel, canvas_),
  PROTOBUF_FIELD_OFFSET(::com::alimin::fk::pb::FkPictureModel, layers_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::com::alimin::fk::pb::FkPictureModel)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::com::alimin::fk::pb::_FkPictureModel_default_instance_),
};

const char descriptor_table_protodef_FkPictureModel_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024FkPictureModel.proto\022\020com.alimin.fk.pb"
  "\032\022FkImageLayer.proto\"p\n\016FkPictureModel\022."
  "\n\006canvas\030\001 \001(\0132\036.com.alimin.fk.pb.FkImag"
  "eLayer\022.\n\006layers\030\002 \003(\0132\036.com.alimin.fk.p"
  "b.FkImageLayerb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_FkPictureModel_2eproto_deps[1] = {
  &::descriptor_table_FkImageLayer_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_FkPictureModel_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_FkPictureModel_2eproto = {
  false, false, 182, descriptor_table_protodef_FkPictureModel_2eproto, "FkPictureModel.proto", 
  &descriptor_table_FkPictureModel_2eproto_once, descriptor_table_FkPictureModel_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_FkPictureModel_2eproto::offsets,
  file_level_metadata_FkPictureModel_2eproto, file_level_enum_descriptors_FkPictureModel_2eproto, file_level_service_descriptors_FkPictureModel_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_FkPictureModel_2eproto_getter() {
  return &descriptor_table_FkPictureModel_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_FkPictureModel_2eproto(&descriptor_table_FkPictureModel_2eproto);
namespace com {
namespace alimin {
namespace fk {
namespace pb {

// ===================================================================

class FkPictureModel::_Internal {
 public:
  static const ::com::alimin::fk::pb::FkImageLayer& canvas(const FkPictureModel* msg);
};

const ::com::alimin::fk::pb::FkImageLayer&
FkPictureModel::_Internal::canvas(const FkPictureModel* msg) {
  return *msg->canvas_;
}
void FkPictureModel::clear_canvas() {
  if (GetArenaForAllocation() == nullptr && canvas_ != nullptr) {
    delete canvas_;
  }
  canvas_ = nullptr;
}
void FkPictureModel::clear_layers() {
  layers_.Clear();
}
FkPictureModel::FkPictureModel(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  layers_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:com.alimin.fk.pb.FkPictureModel)
}
FkPictureModel::FkPictureModel(const FkPictureModel& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      layers_(from.layers_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_canvas()) {
    canvas_ = new ::com::alimin::fk::pb::FkImageLayer(*from.canvas_);
  } else {
    canvas_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:com.alimin.fk.pb.FkPictureModel)
}

inline void FkPictureModel::SharedCtor() {
canvas_ = nullptr;
}

FkPictureModel::~FkPictureModel() {
  // @@protoc_insertion_point(destructor:com.alimin.fk.pb.FkPictureModel)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void FkPictureModel::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete canvas_;
}

void FkPictureModel::ArenaDtor(void* object) {
  FkPictureModel* _this = reinterpret_cast< FkPictureModel* >(object);
  (void)_this;
}
void FkPictureModel::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void FkPictureModel::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void FkPictureModel::Clear() {
// @@protoc_insertion_point(message_clear_start:com.alimin.fk.pb.FkPictureModel)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  layers_.Clear();
  if (GetArenaForAllocation() == nullptr && canvas_ != nullptr) {
    delete canvas_;
  }
  canvas_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FkPictureModel::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .com.alimin.fk.pb.FkImageLayer canvas = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_canvas(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .com.alimin.fk.pb.FkImageLayer layers = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_layers(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FkPictureModel::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.alimin.fk.pb.FkPictureModel)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .com.alimin.fk.pb.FkImageLayer canvas = 1;
  if (this->_internal_has_canvas()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::canvas(this), target, stream);
  }

  // repeated .com.alimin.fk.pb.FkImageLayer layers = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_layers_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_layers(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.alimin.fk.pb.FkPictureModel)
  return target;
}

size_t FkPictureModel::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.alimin.fk.pb.FkPictureModel)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .com.alimin.fk.pb.FkImageLayer layers = 2;
  total_size += 1UL * this->_internal_layers_size();
  for (const auto& msg : this->layers_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .com.alimin.fk.pb.FkImageLayer canvas = 1;
  if (this->_internal_has_canvas()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *canvas_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FkPictureModel::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    FkPictureModel::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FkPictureModel::GetClassData() const { return &_class_data_; }

void FkPictureModel::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<FkPictureModel *>(to)->MergeFrom(
      static_cast<const FkPictureModel &>(from));
}


void FkPictureModel::MergeFrom(const FkPictureModel& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.alimin.fk.pb.FkPictureModel)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  layers_.MergeFrom(from.layers_);
  if (from._internal_has_canvas()) {
    _internal_mutable_canvas()->::com::alimin::fk::pb::FkImageLayer::MergeFrom(from._internal_canvas());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FkPictureModel::CopyFrom(const FkPictureModel& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.alimin.fk.pb.FkPictureModel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FkPictureModel::IsInitialized() const {
  return true;
}

void FkPictureModel::InternalSwap(FkPictureModel* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  layers_.InternalSwap(&other->layers_);
  swap(canvas_, other->canvas_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FkPictureModel::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_FkPictureModel_2eproto_getter, &descriptor_table_FkPictureModel_2eproto_once,
      file_level_metadata_FkPictureModel_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
}  // namespace fk
}  // namespace alimin
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::com::alimin::fk::pb::FkPictureModel* Arena::CreateMaybeMessage< ::com::alimin::fk::pb::FkPictureModel >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::alimin::fk::pb::FkPictureModel >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
