// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FkPictureModel.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_FkPictureModel_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_FkPictureModel_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "FkImageLayer.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_FkPictureModel_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_FkPictureModel_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_FkPictureModel_2eproto;
namespace com {
namespace alimin {
namespace fk {
namespace pb {
class FkPictureModel;
struct FkPictureModelDefaultTypeInternal;
extern FkPictureModelDefaultTypeInternal _FkPictureModel_default_instance_;
}  // namespace pb
}  // namespace fk
}  // namespace alimin
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> ::com::alimin::fk::pb::FkPictureModel* Arena::CreateMaybeMessage<::com::alimin::fk::pb::FkPictureModel>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace com {
namespace alimin {
namespace fk {
namespace pb {

// ===================================================================

class FkPictureModel final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.alimin.fk.pb.FkPictureModel) */ {
 public:
  inline FkPictureModel() : FkPictureModel(nullptr) {}
  ~FkPictureModel() override;
  explicit constexpr FkPictureModel(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FkPictureModel(const FkPictureModel& from);
  FkPictureModel(FkPictureModel&& from) noexcept
    : FkPictureModel() {
    *this = ::std::move(from);
  }

  inline FkPictureModel& operator=(const FkPictureModel& from) {
    CopyFrom(from);
    return *this;
  }
  inline FkPictureModel& operator=(FkPictureModel&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FkPictureModel& default_instance() {
    return *internal_default_instance();
  }
  static inline const FkPictureModel* internal_default_instance() {
    return reinterpret_cast<const FkPictureModel*>(
               &_FkPictureModel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FkPictureModel& a, FkPictureModel& b) {
    a.Swap(&b);
  }
  inline void Swap(FkPictureModel* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FkPictureModel* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FkPictureModel* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FkPictureModel>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FkPictureModel& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const FkPictureModel& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FkPictureModel* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.alimin.fk.pb.FkPictureModel";
  }
  protected:
  explicit FkPictureModel(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLayersFieldNumber = 2,
    kCanvasFieldNumber = 1,
  };
  // repeated .com.alimin.fk.pb.FkImageLayer layers = 2;
  int layers_size() const;
  private:
  int _internal_layers_size() const;
  public:
  void clear_layers();
  ::com::alimin::fk::pb::FkImageLayer* mutable_layers(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::alimin::fk::pb::FkImageLayer >*
      mutable_layers();
  private:
  const ::com::alimin::fk::pb::FkImageLayer& _internal_layers(int index) const;
  ::com::alimin::fk::pb::FkImageLayer* _internal_add_layers();
  public:
  const ::com::alimin::fk::pb::FkImageLayer& layers(int index) const;
  ::com::alimin::fk::pb::FkImageLayer* add_layers();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::alimin::fk::pb::FkImageLayer >&
      layers() const;

  // .com.alimin.fk.pb.FkImageLayer canvas = 1;
  bool has_canvas() const;
  private:
  bool _internal_has_canvas() const;
  public:
  void clear_canvas();
  const ::com::alimin::fk::pb::FkImageLayer& canvas() const;
  PROTOBUF_NODISCARD ::com::alimin::fk::pb::FkImageLayer* release_canvas();
  ::com::alimin::fk::pb::FkImageLayer* mutable_canvas();
  void set_allocated_canvas(::com::alimin::fk::pb::FkImageLayer* canvas);
  private:
  const ::com::alimin::fk::pb::FkImageLayer& _internal_canvas() const;
  ::com::alimin::fk::pb::FkImageLayer* _internal_mutable_canvas();
  public:
  void unsafe_arena_set_allocated_canvas(
      ::com::alimin::fk::pb::FkImageLayer* canvas);
  ::com::alimin::fk::pb::FkImageLayer* unsafe_arena_release_canvas();

  // @@protoc_insertion_point(class_scope:com.alimin.fk.pb.FkPictureModel)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::alimin::fk::pb::FkImageLayer > layers_;
  ::com::alimin::fk::pb::FkImageLayer* canvas_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_FkPictureModel_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FkPictureModel

// .com.alimin.fk.pb.FkImageLayer canvas = 1;
inline bool FkPictureModel::_internal_has_canvas() const {
  return this != internal_default_instance() && canvas_ != nullptr;
}
inline bool FkPictureModel::has_canvas() const {
  return _internal_has_canvas();
}
inline const ::com::alimin::fk::pb::FkImageLayer& FkPictureModel::_internal_canvas() const {
  const ::com::alimin::fk::pb::FkImageLayer* p = canvas_;
  return p != nullptr ? *p : reinterpret_cast<const ::com::alimin::fk::pb::FkImageLayer&>(
      ::com::alimin::fk::pb::_FkImageLayer_default_instance_);
}
inline const ::com::alimin::fk::pb::FkImageLayer& FkPictureModel::canvas() const {
  // @@protoc_insertion_point(field_get:com.alimin.fk.pb.FkPictureModel.canvas)
  return _internal_canvas();
}
inline void FkPictureModel::unsafe_arena_set_allocated_canvas(
    ::com::alimin::fk::pb::FkImageLayer* canvas) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(canvas_);
  }
  canvas_ = canvas;
  if (canvas) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:com.alimin.fk.pb.FkPictureModel.canvas)
}
inline ::com::alimin::fk::pb::FkImageLayer* FkPictureModel::release_canvas() {
  
  ::com::alimin::fk::pb::FkImageLayer* temp = canvas_;
  canvas_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::com::alimin::fk::pb::FkImageLayer* FkPictureModel::unsafe_arena_release_canvas() {
  // @@protoc_insertion_point(field_release:com.alimin.fk.pb.FkPictureModel.canvas)
  
  ::com::alimin::fk::pb::FkImageLayer* temp = canvas_;
  canvas_ = nullptr;
  return temp;
}
inline ::com::alimin::fk::pb::FkImageLayer* FkPictureModel::_internal_mutable_canvas() {
  
  if (canvas_ == nullptr) {
    auto* p = CreateMaybeMessage<::com::alimin::fk::pb::FkImageLayer>(GetArenaForAllocation());
    canvas_ = p;
  }
  return canvas_;
}
inline ::com::alimin::fk::pb::FkImageLayer* FkPictureModel::mutable_canvas() {
  ::com::alimin::fk::pb::FkImageLayer* _msg = _internal_mutable_canvas();
  // @@protoc_insertion_point(field_mutable:com.alimin.fk.pb.FkPictureModel.canvas)
  return _msg;
}
inline void FkPictureModel::set_allocated_canvas(::com::alimin::fk::pb::FkImageLayer* canvas) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(canvas_);
  }
  if (canvas) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(canvas));
    if (message_arena != submessage_arena) {
      canvas = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, canvas, submessage_arena);
    }
    
  } else {
    
  }
  canvas_ = canvas;
  // @@protoc_insertion_point(field_set_allocated:com.alimin.fk.pb.FkPictureModel.canvas)
}

// repeated .com.alimin.fk.pb.FkImageLayer layers = 2;
inline int FkPictureModel::_internal_layers_size() const {
  return layers_.size();
}
inline int FkPictureModel::layers_size() const {
  return _internal_layers_size();
}
inline ::com::alimin::fk::pb::FkImageLayer* FkPictureModel::mutable_layers(int index) {
  // @@protoc_insertion_point(field_mutable:com.alimin.fk.pb.FkPictureModel.layers)
  return layers_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::alimin::fk::pb::FkImageLayer >*
FkPictureModel::mutable_layers() {
  // @@protoc_insertion_point(field_mutable_list:com.alimin.fk.pb.FkPictureModel.layers)
  return &layers_;
}
inline const ::com::alimin::fk::pb::FkImageLayer& FkPictureModel::_internal_layers(int index) const {
  return layers_.Get(index);
}
inline const ::com::alimin::fk::pb::FkImageLayer& FkPictureModel::layers(int index) const {
  // @@protoc_insertion_point(field_get:com.alimin.fk.pb.FkPictureModel.layers)
  return _internal_layers(index);
}
inline ::com::alimin::fk::pb::FkImageLayer* FkPictureModel::_internal_add_layers() {
  return layers_.Add();
}
inline ::com::alimin::fk::pb::FkImageLayer* FkPictureModel::add_layers() {
  ::com::alimin::fk::pb::FkImageLayer* _add = _internal_add_layers();
  // @@protoc_insertion_point(field_add:com.alimin.fk.pb.FkPictureModel.layers)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::alimin::fk::pb::FkImageLayer >&
FkPictureModel::layers() const {
  // @@protoc_insertion_point(field_list:com.alimin.fk.pb.FkPictureModel.layers)
  return layers_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace fk
}  // namespace alimin
}  // namespace com

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_FkPictureModel_2eproto
