// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FkRational.proto

#include "FkRational.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace com {
namespace alimin {
namespace fk {
namespace pb {
constexpr FkRational::FkRational(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : num_(0)
  , den_(0){}
struct FkRationalDefaultTypeInternal {
  constexpr FkRationalDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~FkRationalDefaultTypeInternal() {}
  union {
    FkRational _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT FkRationalDefaultTypeInternal _FkRational_default_instance_;
}  // namespace pb
}  // namespace fk
}  // namespace alimin
}  // namespace com
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_FkRational_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_FkRational_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_FkRational_2eproto = nullptr;

const uint32_t TableStruct_FkRational_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::alimin::fk::pb::FkRational, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::com::alimin::fk::pb::FkRational, num_),
  PROTOBUF_FIELD_OFFSET(::com::alimin::fk::pb::FkRational, den_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::com::alimin::fk::pb::FkRational)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::com::alimin::fk::pb::_FkRational_default_instance_),
};

const char descriptor_table_protodef_FkRational_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020FkRational.proto\022\020com.alimin.fk.pb\"&\n\n"
  "FkRational\022\013\n\003num\030\001 \001(\005\022\013\n\003den\030\002 \001(\005b\006pr"
  "oto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_FkRational_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_FkRational_2eproto = {
  false, false, 84, descriptor_table_protodef_FkRational_2eproto, "FkRational.proto", 
  &descriptor_table_FkRational_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_FkRational_2eproto::offsets,
  file_level_metadata_FkRational_2eproto, file_level_enum_descriptors_FkRational_2eproto, file_level_service_descriptors_FkRational_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_FkRational_2eproto_getter() {
  return &descriptor_table_FkRational_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_FkRational_2eproto(&descriptor_table_FkRational_2eproto);
namespace com {
namespace alimin {
namespace fk {
namespace pb {

// ===================================================================

class FkRational::_Internal {
 public:
};

FkRational::FkRational(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:com.alimin.fk.pb.FkRational)
}
FkRational::FkRational(const FkRational& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&num_, &from.num_,
    static_cast<size_t>(reinterpret_cast<char*>(&den_) -
    reinterpret_cast<char*>(&num_)) + sizeof(den_));
  // @@protoc_insertion_point(copy_constructor:com.alimin.fk.pb.FkRational)
}

inline void FkRational::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&num_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&den_) -
    reinterpret_cast<char*>(&num_)) + sizeof(den_));
}

FkRational::~FkRational() {
  // @@protoc_insertion_point(destructor:com.alimin.fk.pb.FkRational)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void FkRational::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void FkRational::ArenaDtor(void* object) {
  FkRational* _this = reinterpret_cast< FkRational* >(object);
  (void)_this;
}
void FkRational::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void FkRational::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void FkRational::Clear() {
// @@protoc_insertion_point(message_clear_start:com.alimin.fk.pb.FkRational)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&num_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&den_) -
      reinterpret_cast<char*>(&num_)) + sizeof(den_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FkRational::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 num = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          num_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 den = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          den_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FkRational::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.alimin.fk.pb.FkRational)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num = 1;
  if (this->_internal_num() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_num(), target);
  }

  // int32 den = 2;
  if (this->_internal_den() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_den(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.alimin.fk.pb.FkRational)
  return target;
}

size_t FkRational::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.alimin.fk.pb.FkRational)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 num = 1;
  if (this->_internal_num() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_num());
  }

  // int32 den = 2;
  if (this->_internal_den() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_den());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FkRational::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    FkRational::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FkRational::GetClassData() const { return &_class_data_; }

void FkRational::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<FkRational *>(to)->MergeFrom(
      static_cast<const FkRational &>(from));
}


void FkRational::MergeFrom(const FkRational& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.alimin.fk.pb.FkRational)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_num() != 0) {
    _internal_set_num(from._internal_num());
  }
  if (from._internal_den() != 0) {
    _internal_set_den(from._internal_den());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FkRational::CopyFrom(const FkRational& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.alimin.fk.pb.FkRational)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FkRational::IsInitialized() const {
  return true;
}

void FkRational::InternalSwap(FkRational* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FkRational, den_)
      + sizeof(FkRational::den_)
      - PROTOBUF_FIELD_OFFSET(FkRational, num_)>(
          reinterpret_cast<char*>(&num_),
          reinterpret_cast<char*>(&other->num_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FkRational::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_FkRational_2eproto_getter, &descriptor_table_FkRational_2eproto_once,
      file_level_metadata_FkRational_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
}  // namespace fk
}  // namespace alimin
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::com::alimin::fk::pb::FkRational* Arena::CreateMaybeMessage< ::com::alimin::fk::pb::FkRational >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::alimin::fk::pb::FkRational >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
